set_targetdir("./")
set_languages("cxx17")

set_toolchains("clang")
set_warnings("allextra", "error")
set_optimize("fastest")
set_symbols("debug")

add_requires("glfw")
add_requires("stb")
add_requires("glad")
add_requires("box2d")
add_requires("nlohmann_json")

includes("submodules/Matrix")
includes("submodules/Toolbox")

target("Engine")
    set_kind("static")
    add_files("srcs/**.cpp")
    add_includedirs("srcs", {public = true})
    add_packages("glfw")
    add_packages("stb")
    add_packages("glad")
    add_packages("box2d")
    add_packages("nlohmann_json")
    add_deps("Matrix")
    add_deps("Toolbox")
