set_targetdir("./")
set_languages("cxx17")

set_toolchains("clang")
set_warnings("allextra", "error")
set_optimize("fastest")
set_symbols("debug")

add_requires("glfw")
add_requires("stb")
add_requires("glad")
add_requires("box2d")

namespace("Matrix")
includes("submodules/Matrix")
namespace_end()

namespace("Toolbox")
includes("submodules/Toolbox")
namespace_end()

target("Engine")
    set_kind("static")
    add_files("srcs/**.cpp")
    add_includedirs("srcs", {public = true})
    add_packages("glfw")
    add_packages("stb")
    add_packages("glad")
    add_packages("box2d")
    add_deps("Matrix::Matrix")
    add_deps("Toolbox::Toolbox")
